### ISSUE TITLE
(3) Implement scripts to stress test cenote [3]

### ISSUE THREAD

**Issue by iamnapo** [AuthEceSoftEng/cenote#11]

**Comment by kyrcha** [comment]
@iamnapo What is the plan on that?

**Comment by kyrcha** [comment]
We have to have increasing clients-requests on one side...and increasing node-storm-cockroachdb processes on the other side.

*Experiment 1:*

- Have 10-50-100 clients to send one JSON every second, with outlier detection and have 1-2-3 processes of node-storm-cockroach. How quickly are they written from receive to db write? The experiment should last until we hit an event count of 1 million events.

*Experiment 2:*
- Have 10-50-100 clients requesting a query with and without outlier detection and have 1-2-3 processes of node-storm-cockroach. What is the response time for a given query? The experiment should be repeated with steps between 1 and 1M events.

**Comment by iamnapo** [comment]
I'll start with these two.

Quick question: How can I test with >1 clients? Isn't it the same to insted test 10-50-100 req/sec?

**Comment by iamnapo** [comment]
I'll start with these two.

Quick question: How can I test with >1 clients? Isn't it the same to instead test 10-50-100 req/sec?

**Comment by kyrcha** [comment]
I.e. processes sending requests ...

**Comment by asymeon** [comment]
@iamnapo check this: https://issel.ee.auth.gr/wp-content/uploads/2016/02/An-integrated-framework-for-enhancing-the-semantic-transformation-editing-and-querying-of-relational-databases.pdf
