### ISSUE TITLE
(0.5) Event names cannot contain dashes or underscores [0.5]

### ISSUE THREAD

**Issue by tsakiridis** [AuthEceSoftEng/cenote#14]
Hello!

As far as I can tell, the event names cannot contain dashes or underscores. I could not find any documentation for this, so I am not sure if this is a bug or a feature. If this is the way it should work, then it should be documented and the server should return a proper response.

Attached you may find a python script which tries to create some events with various names; event names containing dashes or underscores appear to be created (server returns a 202 response), however the events are never made. When underscores are used, names are truncated. Please see the attached file for more.

Thanks!

[cenote-event-names.txt](https://github.com/AuthEceSoftEng/cenote/files/2975654/cenote-event-names.txt)

**Comment by iamnapo** [comment]
Hello. Yes, only lowercase letters and numbers (anywhere but the start) are supported for now. I updated the docs and server's responses' status codes.
