### ISSUE TITLE
(0.5) Payload data cannot have a key with parentheses [0.5]

### ISSUE THREAD

**Issue by tsakiridis** [AuthEceSoftEng/cenote#15]
Hello!

When testing with payload data where a key contains parentheses e.g. 

payload = {"payload": {"data": {"current": 50, "voltage": 1.45, "note(1)": "blabla"}}}

although this is valid in JSON, then this is key is not used if the event exists.

If the event doesn't exist, the event is never created, even though the server returns a proper 202 response.

Please see the attached python script.

If this is intended, this should be documented.

[cenote-keys-with-parentheses.txt](https://github.com/AuthEceSoftEng/cenote/files/2975660/cenote-keys-with-parentheses.txt)

Thanks!

**Comment by iamnapo** [comment]
Same name limitation as https://github.com/AuthEceSoftEng/cenote/issues/14#issuecomment-473912940
