### ISSUE TITLE
(1) Backup plan [3.1]

### ISSUE THREAD

**Issue by kyrcha** [AuthEceSoftEng/cenote#22]

**Comment by kyrcha** [comment]
Need to backup:

- [x] redis (through snapshoting) - mount
- [x] mongob of node servers - mount + physical alternative
- [x] cockroach -mount + physical alternative
- [x] zookeeper - mount

**Comment by klimac** [comment]
I am looking at longhorn and how to make a backup using this tool.

**Comment by klimac** [comment]
mongo backup script is ready.

**Comment by klimac** [comment]
mongo has been installed (5GB) + script
cockroach has been installed (800GB)
redis has been installed (30GB)

**Comment by klimac** [comment]
zookeeper set up:
data: 20GB
datalog:20GB
log:20GB
everything else will be dropped on restart

**Comment by iamnapo** [comment]
Note: Generally, Kafka stores its data in its own zookeeper instance. But, because we already have one running (for storm) we used that one for Kafka too.
