### ISSUE TITLE
(0.5) Relocate load balancer to bare metal [0.5]

### ISSUE THREAD

**Issue by asymeon** [AuthEceSoftEng/cenote#25]

**Comment by klimac** [comment]
Have made a few changes at the current setup (LB @ VM) but those changes have not brought any improvement so far. Details:
- Linux conf: net.core.netdev_max_backlog from 1000 to 2000. 
- Some nginx conf changes.
In addition, I have increased the following specs of the VM:
- RAM from 2 to 4 and then to 6.
- CPU from 2 to 4.
