### ISSUE TITLE
(0.5) Docker permission denied [0.5]

### ISSUE THREAD

**Issue by kyrcha** [AuthEceSoftEng/cenote#3]
@klimac When I type the command `docker ps` I get the following error:

> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/json: dial unix /var/run/docker.sock: connect: permission denied

Probably we need to do this: https://docs.docker.com/install/linux/linux-postinstall/

Do you think it is OK?

**Comment by klimac** [comment]
Try: sudo docker ps
As long as, it is a non-critical VM, I will remove the sudo restriction.
