### ISSUE TITLE
(3) Look and Feel [1]

### ISSUE THREAD

**Issue by kyrcha** [AuthEceSoftEng/cenote#40]
Improve the look and feel of the cenote web application: https://cenote.sidero.services

**Comment by ouzounidis** [comment]
[cenote_screens.pdf](https://github.com/AuthEceSoftEng/cenote/files/3223192/cenote_screens.pdf)

**Comment by iamnapo** [comment]
(Done on https://github.com/AuthEceSoftEng/cenote-api/commit/d74fa0e11a65d6fd25775bc58e7d9e3a0890f667)

**Comment by kyrcha** [comment]
Possible improvements:

- [ ] Add labels everywhere
- [ ] Add project description
- [x] Projects as list
- [ ] Add pagination
- [ ] Add activity icon 
- [ ] Collections as a left hand list
