### ISSUE TITLE
(0.5) Commands cenote [0]

### ISSUE THREAD

**Issue by klimac** [AuthEceSoftEng/cenote#41]
Upload a txt file with the commands that should be executed, so a new instance of the cenote can be deployed.
Commands like, cockroach: create user ...

**Comment by iamnapo** [comment]
Based on [README](https://github.com/AuthEceSoftEng/cenote#prerequisites), we use:

- In kafka: `kafka-topics.sh --create --zookeeper zoo:2181 --topic cenoteIncoming --partitions 36 --replication-factor  1`
- In cockroach:
  - `CREATE USER cockroach;`
  - `CREATE DATABASE cenote`;
  - `GRANT ALL ON DATABASE cenote TO cockroach;`
