### ISSUE TITLE
(0.5) Cenote website design [0.5]

### ISSUE THREAD

**Issue by kyrcha** [AuthEceSoftEng/cenote#44]
Design proposal for https://authecesofteng.github.io/cenote/ 
Similar sites:
  - http://s-case.github.io/
  - http://cassandra.apache.org/

**Comment by kyrcha** [comment]
@ouzounidis Hi Akis, can you find some icons and a background image for the cenote website? Thanks

**Comment by ouzounidis** [comment]
Here you are
[cenote_screen_website.pdf](https://github.com/AuthEceSoftEng/cenote/files/3391751/cenote_screen_website.pdf)
[Cenote_icons.zip](https://github.com/AuthEceSoftEng/cenote/files/3391753/Cenote_icons.zip)

**Comment by kyrcha** [comment]
Completed: https://authecesofteng.github.io/cenote/
