### ISSUE TITLE
(0.5) Inconsistency between stored and retrieved value for a number stored as string [0.5]

### ISSUE THREAD

**Issue by tsakiridis** [AuthEceSoftEng/cenote#45]
Hello,

suppose I submit some data where one key has a string which actually contains a number, e.g.
`{"key": "000000"}`

If I submit a simple get request, then this is returned as `{"key": 0}` (note that the string has been converted to an int. If I filter the data containing the key with the value "000000" they are properly returned (but they value on the results is 0), whereas querying for data containing the key-value pair of `{"key": 0}` returns none.

So it looks like the value is stored properly, but when the data are extracted there is some inconsistency - maybe a conversion which returns a number instead of the string.

Attached a small python script as .txt file which showcases the problem.

Please let me know if you need further clarifications.

[testStringNumbers.txt](https://github.com/AuthEceSoftEng/cenote/files/3289500/testStringNumbers.txt)

**Comment by iamnapo** [comment]
Fixed in https://github.com/AuthEceSoftEng/cenote-api/commit/973909066c248ae8d814f7a227360852ff4de6f2, will push to prod soon.
