### ISSUE TITLE
(0.5) Getting a connect ECONNREFUSED to 10.42.1.101:26257 error message [0.5]

### ISSUE THREAD

**Issue by tsakiridis** [AuthEceSoftEng/cenote#47]
Hello,

since this morning some of my GET requests have been failing. The returned body is:

`
'{"ok":false,"results":"BadQueryError","message":"connect ECONNREFUSED 10.42.1.101:26257"}'
`

I haven't changed the code on my part and this appears to occur somewhat stochastically.
I saw on the root README.md that you use 10.43.* for Storm so maybe it has to do something with that?

Please advise!

Thanks :)

**Comment by klimac** [comment]
Cockroach: one replica is marked as faulty. There is not option to restore it.
Longhorn maybe should be dropped.
![image](https://user-images.githubusercontent.com/13903176/59506262-76cc4e80-8eb0-11e9-9a10-140662e4d694.png)

Scheduler is unavailable. Due to this reason new PODs can not be deployed.

**Comment by klimac** [comment]
Maybe rancher should be dropped and install only the kubernetes platform.

**Comment by iamnapo** [comment]
(Moved to new DB, so I'm closing this)
