### ISSUE TITLE
(0.5) Bug in Collaborators that redirects to a project specific project when I try to login [0.5]

### ISSUE THREAD

**Issue by kyrcha** [AuthEceSoftEng/cenote#48]
![Screenshot 2019-06-15 15 39 11](https://user-images.githubusercontent.com/400161/59551544-f37c2d00-8f83-11e9-8cd0-d5520ef3131c.png)

**Comment by kyrcha** [comment]
Only works in an incognito Chrome window. As I can see there are some leftovers in the local storage. Perhaps add some logic to handle them appropriately.

![Screenshot 2019-06-18 12 47 19](https://user-images.githubusercontent.com/400161/59672037-6c1efb80-91c7-11e9-9f96-5e9fd9053dc1.png)
![Screenshot 2019-06-18 12 46 49](https://user-images.githubusercontent.com/400161/59672038-6cb79200-91c7-11e9-985c-0a85408710bf.png)

**Comment by iamnapo** [comment]
(I did already, just forgot to keep the issue open until I push them to production)
