### ISSUE TITLE
(0.5) How to denote property type? [0.5]

### ISSUE THREAD

**Issue by etsardou** [AuthEceSoftEng/cenote#49]
For example I am sending a timestamp and it is automatically denoted as Decimal, thus I cannot make comparisons to cenote$timestamp, or cenote$created_at

**Comment by kyrcha** [comment]
Could you provide the example request?

**Comment by etsardou** [comment]
payload is ```{"payload": [{"timestamp": 1561715351, "data": {"dispatchtimestamp": 1561715351.023147, "current": 3.0, "reactive": -855.8816238008262, "voltage": 238.4, "active": 1020, "powerl1": 100, "phaseanglecurrentvoltagel1": 320}}]}```, data are

![Screenshot from 2019-06-28 12-49-47](https://user-images.githubusercontent.com/5663091/60334040-3c2fdf00-99a3-11e9-83da-7f9a0592a36b.png)

**Comment by kyrcha** [comment]
I see. Well we only have two time stamps defined as timestamps in the database...created at and timestamp. Perhaps we can look into sending a property in a string time stamp format and not in milliseconds to be parsed as a time stamp and then do calculations and filtering with it.
