### ISSUE TITLE
(0.5) Question: What is the difference between cenote$created_at and cenote$timestamp, cause they have 3 hours difference [0.5]

### ISSUE THREAD

**Issue by etsardou** [AuthEceSoftEng/cenote#50]
![Screenshot from 2019-06-28 12-45-47](https://user-images.githubusercontent.com/5663091/60333822-ae53f400-99a2-11e9-8722-99fdbc21e6fe.png)

**Comment by kyrcha** [comment]
Created at is set by the system and you cannot change it. It is the time the event was written. The timestamp is changeable and if you do not provide a value it should be the same as created at.

**Comment by kyrcha** [comment]
As for the difference we will look into it.

**Comment by etsardou** [comment]
Is it a full timestamp (up to ns) or up to seconds?

**Comment by etsardou** [comment]
Ok its ms ;)
