### ISSUE TITLE
(0,5) Wrong date stored in cenote$timestamp [0.5]

### ISSUE THREAD

**Issue by etsardou** [AuthEceSoftEng/cenote#53]
Send this payload:
```(99, '{"payload": [{"timestamp": 1561998961.281431, "data": {"current": 0.4, "reactive": -119.17, "voltage": 238.5, "active": 100, "powerl1": 70, "phaseanglecurrentvoltagel1": 310}}]}')```

and the record I got was 
![image](https://user-images.githubusercontent.com/5663091/60453160-0c016e00-9c39-11e9-95e5-d893774b300c.png)

The timestamp in payload is:
```
GMT: Monday, July 1, 2019 4:36:01.281 PM
Your time zone: Monday, July 1, 2019 7:36:01.281 PM GMT+03:00 DST
```

**Comment by iamnapo** [comment]
Hello, 

This is because we treat every timestamp as if it's in ms. (So you still provided a "valid" timestamp)

**Comment by iamnapo** [comment]
Would it be better to add a check if the timestamp is after eg 1/1/2000 and if not, discard it?

**Comment by etsardou** [comment]
Aha ok.. If you have documented it in docs is ok. Nevertheless, have in mind that the unix timestamp is in seconds, so you'll unintentionally get a lot of wrong data..

https://en.wikipedia.org/wiki/Unix_time

**Comment by iamnapo** [comment]
Yes, I used ms cause that's Node.js' [time value](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.1).

I added a clearer warning in the docs, and updated the response message, if the timestamp is before 1/1/2000

**Comment by mstamatiadou** [comment]
I have the same issue here... It's not clear to me what the solution is. 
I have a payload: 
`{"payload": [{"data": {"active": 1010, "powerl1": 90, "current": 3.0, "voltage": 237.4, "phaseanglecurrentvoltagel1": 320, "reactive": -847.4906274890534}, "timestamp": 1562070375.756122}]}`

which has a timestamp: 
2019-07-02 12:26:15.756122+00:00     
equal to: 1562070375.756122 (in ms) 

The cenote record I get is: 
![image](https://user-images.githubusercontent.com/914490/60513244-635a1980-9cdf-11e9-9e74-e02d93f02644.png)

**Comment by etsardou** [comment]
Just send the timestamp * 1000 (so as to be in ms instead of seconds)

**Comment by mstamatiadou** [comment]
Simple as that! Thanks!
