### ISSUE TITLE
(0,5) Different timezone representation between cenote$timestamp and cenote$created_at  [0.5]

### ISSUE THREAD

**Issue by mstamatiadou** [AuthEceSoftEng/cenote#56]
When POSTing an event to cenote with a current timestamp in UTC **using `utcnow()`** the UI returns timestamp and created_at values with a 3-hour shift. Example:  
![image](https://user-images.githubusercontent.com/914490/60598914-39bff180-9db6-11e9-9384-09b1657f368f.png)

When POSTing an event to cenote with a current timestamp in UTC **using `now(pytz.utc)`** the UI returns timestamp and created_at values with a 6-hour shift.

**Comment by iamnapo** [comment]
Hopefully fixed in https://github.com/AuthEceSoftEng/cenote-api/commit/f7a94d8844ecb42dc8aa6c328e97235ca67d9e2f, https://github.com/AuthEceSoftEng/cenote-api/commit/599fcad622f121b08659441c425e4762a6c1bd6a

Can you check again?

**Comment by mstamatiadou** [comment]
Seems fine!
