### ISSUE TITLE
(0,5) Logging out on refresh page [0.5]

### ISSUE THREAD

**Issue by mstamatiadou** [AuthEceSoftEng/cenote#57]
When refreshing the cenote UI on https://cenote.sidero.services/projects, it logs the current user out and redirects to the log in page.

**Comment by iamnapo** [comment]
Hello,

That's strange. I tried it in Chrome and Firefox and cannot reproduce it neither in normal nor in incognito browsing.

What browser are you using?

**Comment by mstamatiadou** [comment]
I'm using Chrome. And it happens every time I refresh.

**Comment by iamnapo** [comment]
After discussion, the problem was that the `Allow sites to save and read cookie data (recommended)` setting in `chrome://settings/content/cookies` needed to be on.
