### ISSUE TITLE
(5) Create a local Cenote dev environment [5]

### ISSUE THREAD

**Issue by johnantonn** [AuthEceSoftEng/cenote#58]
Install the required packages and build Cenote end-to-end in a local dev environment. This will help acquire a basic knowledge of the system as well as have a working environment for future issues.

**Comment by johnantonn** [comment]
I have proceeded with the installation of all the required packages, as instructed by the [cenote readme](https://github.com/AuthEceSoftEng/cenote):
- Node
- Mongo
- Cockroach
- ZooKeper
- Kafka
- Storm
- Redis

I followed the instructions as best as I could (they are not as clear) and when I try to submit the cenote-write topology to the storm cluster (instance), I get the error:

`Error: Could not find or load main class org.apache.storm.command.ConfigValue
Error: Could not find or load main class org.apache.storm.command.ConfigValue
Running: java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/usr/local -Dstorm.log.dir=/usr/local/logs -Djava.library.path= -Dstorm.conf.file= -cp /usr/local/*:/usr/local/lib/*:write-0.1.0-jar-with-dependencies.jar:/usr/local/conf:/usr/local/bin: -Dstorm.jar=write-0.1.0-jar-with-dependencies.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} com.issel.cenote.WriteTopology WriteTopology
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/storm/topology/IRichSpout
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.topology.IRichSpout
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 7 more
`

**Comment by iamnapo** [comment]
What java version are you using? We are using `openjdk version "1.8.0_212"`. Maybe that's the issue?

**Comment by johnantonn** [comment]
> What java version are you using? We are using `openjdk version "1.8.0_212"`. Maybe that's the issue?

Hello @iamnapo, thanks for the reply! I tried both openjdk and Oracle JDK (version "1.8.0_241"). The issue seemed to be in the symlinks of storm that I had created. Running the script from the bin directory solved it and the topology was uploaded successfully.

Now I have another issue with the cenote-api repo, it seems there's an issue with npm(probably the vm), when I try installing the dependencies I get a memory error:

`Illegal instruction (core dumped)ata: sill install loadAllDepsIntoIdealTree`

I tried the same with eeris-app just to ensure that the issue is machine-related and not repo-related and the same error appears. Any ideas?

**Comment by iamnapo** [comment]
No clue. Maybe try using [nvm](https://github.com/nvm-sh/nvm).

**Comment by johnantonn** [comment]
I tried removing and installing nodejs again and it worked! Thanks for your time @iamnapo.

**Comment by johnantonn** [comment]
The development environment is ready and it seems to be working correctly (tested the front-end in various ways).

An issue I'm facing is that **cenote-api** should ideally be installed on a local machine with the capability to run VS Code and modify the code accordingly. With a machine running linux, this would be fairly easy to do. On Windows it might be a bit more difficult to install the dependencies required.

**Comment by johnantonn** [comment]
The establishment of a local dev environment for cenote takes longer than anticipated.

Current progress: managed to install cenote-api locally on my Windows machine in order to be able to change it via VS Code UI. Essentially I did the following:

- Installed `cygwin`, required for `gcc `and `librdkafka-dev` libraries to run on Windows. Had some issues with the naming and packages but managed to solve them.
- Installed dependencies of cenote-api, however the npm `postinstall `script does not run correctly on cygwin environment. I had to debug and run the `npm i` command manually for both server and client independently.
- After doing tests in the web UI, it seems that there is something wrong with the kafka installation because events are not written successfully (the requests are timed out).

Looking into the latter.

**Comment by johnantonn** [comment]
https://code.visualstudio.com/docs/remote/wsl

**Comment by johnantonn** [comment]
After witnessing poor performance to the existing dev enviornment (vm), I decided to repeat the installation to my laptop and more specifically to the Windows Subsystem for Linux [(https://code.visualstudio.com/docs/remote/wsl).](https://code.visualstudio.com/docs/remote/wsl) All of the components are now running there according to the installation instructions found in [cenote](https://github.com/AuthEceSoftEng/cenote) readme.

Something that is not referenced in the readme of [cenote-write](https://github.com/AuthEceSoftEng/cenote-write) is that it requires the linked repos to be cloned by using this command:

`git clone --recurse-submodules -j8 https://github.com/AuthEceSoftEng/cenote-write.git`

and also it requires two .env files to be filled with the appropriate values, in the root directory as well as in the `python-src/resources/CockroachHandler` linked directory.

Finally, I have created a script that executes all the service binaries and keeps their logs. It requires environmental variables to be set; for more info check inside.

[start-services.zip](https://github.com/AuthEceSoftEng/cenote/files/4359804/start-services.zip)

After doing all of the above, the issue of events not being written to the database is still present..

**Comment by johnantonn** [comment]
Created a script that executes all the service binaries and keeps their logs.

**Comment by johnantonn** [comment]
After inspecting the storm worker logs, there seemed to be an issue with the JVM and by searching through the web there are reports to downgrade the version of Java to 8. I did that and relaunched the installation, now there seems to be another issue with a python module, as indicated by the screenshot below:

![Screenshot_1](https://user-images.githubusercontent.com/8168416/77235380-c701db00-6bbd-11ea-9dc7-31dc9751116a.png)

**Comment by iamnapo** [comment]
In the root of the cenote-write repository do:
```sh
$ cd python-src/resources/CockroachHandler
$ pip3 install -r requirements.txt
```

**Comment by johnantonn** [comment]
I killed the topology from storm, ran the suggested steps, rebuilt the package and passed it to storm. After running everything from scratch, I now get the below error associated with the storm workers:

![Screenshot_1](https://user-images.githubusercontent.com/8168416/77303325-7395a700-6cfb-11ea-98c3-c0070d45d692.png)

which indicates that the data are being passed to kafka, however storm fails to read them from kafka spout and write them to cockroach.

**Comment by johnantonn** [comment]
Managed to get it working by deleting all data/log directories from zookeeper/kafka as well and re-running all scripts. Now the posted events are correctly written to cockroach db, while I have the UIs available as well:

- Mongo at 8090
- Storm at 8080

I will open a separate issue for updating the repos' readmes and installation instructions.

Closing the issue.
