### ISSUE TITLE
(1) Fix issue with create project [0]

### ISSUE THREAD

**Issue by asymeon** [AuthEceSoftEng/cenote#66]
When I log in and Create project then I get Internal server error 500 and the project is not created.

**Comment by iamnapo** [comment]
Hello,

I tried both a couple of days ago and just now, and can create projects just fine. Are you still experiencing this?

@johnantonn Can you see if you are facing this too?

**Comment by johnantonn** [comment]
Hello, I can create projects without issues as well. @iamnapo
